name: Upload to OSS

on:
  push:
    branches:
    - main
    tags:
    - 'v[0-9].[0-9]+.[0-9]+**'

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Variables
        run: |
          echo "project_name=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV
          echo "release_file=${GITHUB_REPOSITORY#*/}.tar.gz" >> $GITHUB_ENV

      - name: Install ossutil
        run: |
          cd ..
          wget -q https://gosspublic.alicdn.com/ossutil/1.7.14/ossutil64
          chmod 755 ossutil64

      - name: Upload to OSS
        run: |
          cd ..
          tar -czvf ${{ env.release_file }} --exclude=${{ env.project_name }}/.github --exclude=${{ env.project_name }}/.git ./${{ env.project_name }}
          ./ossutil64 cp ${{ env.release_file }} oss://llaoj/${{ env.project_name }}/ --update --meta x-oss-object-acl:public-read -e ${{ secrets.OSS_ENDPOINT }} -i ${{ secrets.OSS_ACCESS_KEY_ID }} -k ${{ secrets.OSS_SECRET_ACCESS_KEY }}