name: Build container image

on:
  push:
    branches:
    - main
    tags:
    - 'v[0-9].[0-9]+.[0-9]+**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Variables
        run: |
          echo "project_name=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV
          echo "release_file=${GITHUB_REPOSITORY#*/}.zip" >> $GITHUB_ENV

      - name: Install ossutil
        run: |
          env
          wget -q -O $HOME/ossutil64 https://gosspublic.alicdn.com/ossutil/1.7.14/ossutil64
          chmod 755 $HOME/ossutil64
          ls -la $HOME/

      - name: Upload to OSS
        run: |
          zip  -r ${{ env.release_file }}  ./ -x ".github/" ".git/"
          ls -la ../
          $HOME/ossutil64 cp ${{ env.release_file }} oss://llaoj/${{ env.project_name }}/ --update --meta x-oss-object-acl:public-read --meta x-oss-object-acl:public-read -e {{ secrets.OSS_ENDPOINT }} -i {{ secrets.OSS_ACCESS_KEY_ID }} -k {{ secrets.OSS_SECRET_ACCESS_KEY }}