name: Build container image

on:
  push:
    branches:
    - main
    tags:
    - 'v[0-9].[0-9]+.[0-9]+**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Variables
        run: |
          echo "project_name=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV

      - name: Install ossutil
        run: |
          wget https://gosspublic.alicdn.com/ossutil/1.7.14/ossutil64
          chmod 755 ossutil64

      - name: Upload to OSS
        run: |
          zip  -r {{ env.project_name }}.zip  ./
          ls -la
          ./ossutil64 cp {{ env.project_name }}.zip oss://llaoj/{{ env.project_name }}/ --update --meta x-oss-object-acl:public-read --meta x-oss-object-acl:public-read -e {{ secrets.OSS_ENDPOINT }} -i {{ secrets.OSS_ACCESS_KEY_ID }} -k {{ secrets.OSS_SECRET_ACCESS_KEY }}