name: Build Container Image

on:
  push:
    branches:
    - main
    tags:
    - 'v[0-9].[0-9]+.[0-9]+**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Variables
        run: |
          APP_NAME=${GITHUB_REPOSITORY//\//_}
          GIT_TAG=${GITHUB_REF#refs/tags/}
          echo "image=${{ secrets.REGISTRY }}/${APP_NAME}:${GIT_TAG}" >> $GITHUB_ENV

      - name: Build and push image to ACR
        run: |
          docker build -t ${{ env.image }} .
          docker login -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_PASSWORD }} ${{ secrets.REGISTRY }}
          docker push ${{ env.image }}